### ISSUE TITLE
Add support for arrayFilters in bsonkit.Apply

### ISSUE THREAD

**Issue by amreo** [256dpi/lungo#1]
https://godoc.org/github.com/256dpi/lungo/mongokit#Apply
https://docs.mongodb.com/manual/reference/method/db.collection.update/

I want to change the values of some items of a array. I think that Apply needs a another param.

**Comment by 256dpi** [comment]
Array filters have not yet been implemented, hence the missing parameter to `Apply`. Once the implementation lands it will be added.

**Comment by 256dpi** [comment]
Done!
